# fly.toml app configuration file generated for dawn-fog-6414 on 2023-08-14T21:19:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-fog-6414"
primary_region = "ams"

[build]
  image = "anebesna/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dsppfd1tw"
  ClodinarySettings__ApiKey="785818285241254" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
